name: Update ads.txt daily

on:
    workflow_dispatch: {}
    schedule:
        - cron: "17 3 * * *" # daily at 03:17 UTC; adjust as you like

jobs:
    sync-ads:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - - name: Fetch ads.txt from AdstxtManager (robust)
    run: |
        set -euo pipefail

        URL="https://srv.adstxtmanager.com/19390/dropgenerator.com"  # <-- ensure your apex domain here
        OUT="ads.txt.new"

        # Try up to 5 times with small backoff; follow redirects; 60s timeout
        STATUS=$(curl -sS -L --retry 5 --retry-delay 5 --max-time 60 \
                     -w "%{http_code}" -o "$OUT" "$URL")

        echo "HTTP status: $STATUS"

        if [ "$STATUS" -ne 200 ]; then
          echo "Non-200 from AdstxtManager. Showing first 200 bytes of body for diagnosis:"
          head -c 200 "$OUT" || true
          # Fail the job with a clearer message
          exit 22
        fi

        if [ ! -s "$OUT" ]; then
          echo "Downloaded file is empty; aborting."
          exit 22
        fi

        # Only replace if changed
        if [ -f ads.txt ] && diff -q "$OUT" ads.txt >/dev/null; then
          echo "No change to ads.txt."
          rm -f "$OUT"
          exit 0
        fi

        mv "$OUT" ads.txt

          - name: Commit & push if changed
            run: |
              if [ -n "$(git status --porcelain)" ]; then
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git add ads.txt
                git commit -m "chore: daily ads.txt sync"
                git push
              fi
