name: Update ads.txt daily

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"   # daily at 03:17 UTC; adjust as you like

jobs:
  sync-ads:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch ads.txt from AdstxtManager
        run: |
          set -euo pipefail
          URL="https://srv.adstxtmanager.com/19390/dropgenerator.com"
          curl -fsSL "$URL" -o ads.txt.new
          if [ ! -s ads.txt.new ]; then
            echo "Downloaded ads.txt is empty; aborting."
            exit 1
          fi
          if [ -f ads.txt ] && diff -q ads.txt.new ads.txt >/dev/null; then
            echo "No change."
            exit 0
          fi
          mv ads.txt.new ads.txt

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add ads.txt
            git commit -m "chore: daily ads.txt sync"
            git push
          fi